function b = bVector(dth1,dth2,dth3,g,l1,l2,l3,m1,m2,m3,th1,th2,th3)
%BVECTOR
%    B = BVECTOR(DTH1,DTH2,DTH3,G,L1,L2,L3,M1,M2,M3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    12-Dec-2016 10:23:20

t2 = dth1.^2;
t3 = cos(th1);
t4 = sin(th1);
t5 = dth2.^2;
t6 = l1.*t2.*t3;
t7 = cos(th2);
t8 = sin(th2);
t9 = dth3.^2;
t10 = l2.*t5.*t7;
t11 = cos(th3);
t12 = sin(th3);
b = [0.0;g.*m1.*2.0;0.0;-g.*m2;0.0;-g.*m3;0.0;0.0;0.0;t6;-l1.*t2.*t4;l1.*t2.*t3.*-2.0-l2.*t5.*t7;l1.*t2.*t4.*-2.0-l2.*t5.*t8;t6+t10+l3.*t9.*t11.*(1.0./2.0);l1.*t2.*t4.*-2.0-l2.*t5.*t8.*2.0-l3.*t9.*t12;-t6-t10-l3.*t9.*t11;-l1.*t2.*t4-l2.*t5.*t8-l3.*t9.*t12];
