function b = bVector(d1,d2,d3,dth1,dth2,dth3,g,l1,l2,m1,m2,m3,th1,th2,th3)
%BVECTOR
%    B = BVECTOR(D1,D2,D3,DTH1,DTH2,DTH3,G,L1,L2,M1,M2,M3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    12-Dec-2016 10:56:46

t2 = cos(th1);
t3 = sin(th1);
t4 = dth1.^2;
t5 = t2.^2;
t6 = t3.^2;
t7 = t5+t6;
t8 = 1.0./t7;
t9 = cos(th2);
t10 = sin(th2);
t11 = dth2.^2;
t12 = t9.^2;
t13 = t10.^2;
t14 = t12+t13;
t15 = 1.0./t14;
t16 = cos(th3);
t17 = sin(th3);
t18 = l1.*t2.*t4.*t8;
t19 = dth3.^2;
t20 = t16.^2;
t21 = t17.^2;
t22 = t20+t21;
t23 = 1.0./t22;
t24 = l1.*t3.*t4.*t8;
b = [0.0;-g.*m1;0.0;-g.*m2;0.0;-g.*m3;0.0;0.0;0.0;d1.*t2.*t4.*t8;d1.*t3.*t4.*t8;t18+d2.*t9.*t11.*t15;t24+d2.*t10.*t11.*t15;t18+d3.*t16.*t19.*t23+l2.*t9.*t11.*t15;t24+d3.*t17.*t19.*t23+l2.*t10.*t11.*t15];
